# Generated by Django 3.0.6 on 2020-10-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201004_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default='not given', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='not given', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.TextField(default='not given', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.TextField(default='not given', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='not given', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.TextField(default='not given', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.TextField(blank=True, default='not given', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.TextField(default='not given', max_length=100),
        ),
    ]
